dubbo:
  application:
    name: doubbo-consumer
  protocol:
    name: dubbo
    port: 20880
    server: netty4
  registry:
    address: nacos://58.49.160.90:8848
  provider:
    timeout: 1000

server:
  port: 9090

spring:
  application:
    name: doubbo-consumer
